project_id = "vtckfsguxmxsdcnehqju"

[functions.curriculum-analysis]
verify_jwt = false

[functions.interview-dojo]
verify_jwt = false

[functions.communication-lab]
verify_jwt = false

[functions.career-gps]
verify_jwt = false

[functions.erp-simulator]
verify_jwt = false

[functions.spreadsheet-arena]
verify_jwt = false

[functions.bsc-strategic]
verify_jwt = false