// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtckfsguxmxsdcnehqju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0Y2tmc2d1eG14c2RjbmVocWp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NjYzMzcsImV4cCI6MjA3NDI0MjMzN30.7hqGFtWeSklRV4MUon5Erq1cusWt2Xqv_GcOlcCn3vI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});